### ISSUE TITLE
Remove "run unit test" from github workflow when answered "no unit test" during algokit init wizard

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-react-frontend-template#20]
If the user says no to "create unit test" during algokit wizard, the github workflow automatically fails as it includes "run unit test". The user manually has to delete this workflow to get it to work.

**Comment by aorumbayev** [comment]
Addressed in https://github.com/algorandfoundation/algokit-react-frontend-template/pull/22
