### ISSUE TITLE
"Failed to construct 'URL': Invalid URL" error when deployed on Vercel

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-react-frontend-template#21]
I tried deploying the default react template to vercel and this is what happened. 

<img width="1512" alt="image" src="https://github.com/algorandfoundation/algokit-react-frontend-template/assets/52557585/55cccfae-b951-48e4-bbbd-783aefe3cbde">

Live app here: https://test-7d3a9jzpp-chris-kims-projects-a3cf62d3.vercel.app/

**Comment by aorumbayev** [comment]
@iskysun96 how exactly have you configured the environment variables. The pr here adds explicit step by step instructions on each env variable that needs updating, we haven't initially made them explicit given that its a production template and user may have their own preference on how they want to use netlify or vercel but the docs in the pr expand on default setup by the repo. https://github.com/algorandfoundation/algokit-react-frontend-template/pull/22

**Comment by iskysun96** [comment]
I have them configured to testnet. (uncommented code for testnet) and then marked `VITE_ENVIRONMENT=production`

**Comment by iskysun96** [comment]
I realized I have to add the environment variables to the github repo or to vercel to make it work. However, even after I did that (Add envs to github repo and vercel) it still doesn't work. 

Could this have to do with the way you import in the env variables? The way vite handles this is different. 
https://stackoverflow.com/questions/75172554/environment-variables-with-vite-react-ts-and-vercel

**Comment by aorumbayev** [comment]
Addressed by adding explicit guidelines into the readme explaining env vars required to be set on repo variables/secrets in order for default deployment pipeline to prefill env vars in netlify/vercel build bundles - https://github.com/algorandfoundation/algokit-react-frontend-template/pull/22
